version: "1"
rules:
  #- base: master
  - base: master
    upstream: KelvinTegelaar:master
    mergeMethod: merge
  # Comment out dev
  #- base: dev
  #  upstream: KelvinTegelaar:dev
  #  mergeMethod: none
